In [2]:
import numpy as np



In [3]:
a = np.array([(7, -1, 4, 2)])
b = np.array([(13, 6, 9, 21)])
c = a + b

print(c)

[[20  5 13 23]]


In [4]:
A = np.array([(9, 3, 1), (2, 4, 11), (-2, 0, 5)])
B = np.array([(6, 7, 2), (8, -2, 1), (4, 1, 0)])
C = A - B
d = np.dot(A, B)
print(C, "\n")

print(d)

[[ 3 -4 -1]
 [-6  6 10]
 [-6 -1  5]] 

[[82 58 21]
 [88 17  8]
 [ 8 -9 -4]]


In [5]:
A = np.array([(2, 9, 8), (1, 6, 3)])
B = np.array([(-3, 4, 6), (7, 1, 5)])
Bt = B.T

d = np.dot(A, Bt)
print(d)

[[78 63]
 [39 28]]


In [6]:
A = np.array([[3, 2, 1], [5, 3, 4], [1, 1, -1]])
b = np.array([1, 2, 1])
X = np.dot((np.linalg.inv(A)),b)
print(X)

[-4.  6.  1.]
